---
title: "Aulas"
---

- [Inferências sobre Vetores de Médias](/aulas/Inferencias_Medias/Teste_medias.html "Inferências sobre Vetores de Médias"){aria-label="Inferências sobre Vetores de Médias"}

- [Testes de Hipóteses sobre Matrizes de Covariâncias](/aulas/Inferencia_Covariancias/Teste_covariancias.html "Testes de Hipóteses sobre Matrizes de Covariâncias"){aria-label="Testes de Hipóteses sobre Matrizes de Covariâncias"}

- [Análise de Variância Multivariada](/aulas/Manova/manova.html "Manova"){aria-label="Manova"}

- [Análise de Regressão Multivariada](/aulas/Regressao_Multivariada/regressao.html "Regressão Multivariada"){aria-label="Regressão Multivariada"}

- [Escalonamento Multidimensional (MDS)](/aulas/Escalonamento/escalonamento.html "Escalonamento Multidimensional"){aria-label="Escalonamento Multidimensional"}

- [Análise de Correlação Canônica](/aulas/Correlacao_Canonica/canonica.html "Análise de Correlação Canônica"){aria-label="Análise de Correlação Canônica"}

- Análise de Correspondência
