---
title: "Cronograma da disciplina"
tbl-colwidths: [5,10,30,5,5,5,5,5,5,5]
---

Esta página contém um esboço dos tópicos, conteúdos e tarefas para o semestre. Este cronograma será atualizado conforme o semestre avança.

<!-- https://fontawesome.com/search?o=r&m=free -->
<!-- https://jpswalsh.github.io/academicons/ -->


<!-- [{{< fa file-pdf size=2xl >}}](/weeks/week-1.html#prepare){aria-label="Week 1 summary"}  |  [️](/slides/lec-1.html "Lecture slides"){aria-label="Lecture 1 slides"}  |       [{{< fa laptop-file size=2xl >}}](/ae/ae-0-movies.html "Application exercise"){aria-label="Application Exercise 0 instructions"} -->

<!-- {{< fa brands r-project size=2xl >}}  -  scripts -->
<!-- {{< fa file-powerpoint size=2xl >}}   -  slides -->
<!-- {{< fa laptop-file size=2xl >}}  -  estudo de caso -->
<!-- {{< fa file-pdf size=2xl >}}  -  artigo -->
<!-- {{< fa table size=2xl >}}  -  tabelas estatisticas -->
<!-- {{< fa-solid fa-file-lines size=2xl >}}  -  exercicios -->

::: column-screen-inset-right
| Semana | Data | Tópico | Artigo | Slides |EC |LE |Script  | Avaliação | Projeto |
|:------:|--------|--------|:------:|:------:|:------:|:------:|:------:|:------:|:------:|
|  [1](programacao/semana-1.html)  | Seg, 05/05 | Apresentação da disciplina |  |  |  |  | | 
|  | Qua, 07/05 | Não haverá aula | |  | | | | | |
|  [2](programacao/semana-2.html)  | Sex, 16/05 | Inferência sobre vetores de médias | | [{{< fa file-powerpoint size=2xl >}}](/aulas/Inferencias_Medias/Teste_medias.html "Inferência sobre vetores de médias"){aria-label="Inferência sobre vetores de médias"} | | | | | |
|  [3](programacao/semana-3.html)  | Sex, 23/05 | Inferência sobre vetores de médias | | [{{< fa file-powerpoint size=2xl >}}](/aulas/Inferencias_Medias/Teste_medias.html#/região-de-confiança-do-vetor-de-médias "Inferência sobre vetores de médias"){aria-label="Inferência sobre vetores de médias"} | | | | | |
|  [4](programacao/semana-4.html)  | Sex, 30/05 | Inferência sobre vetores de médias | | [{{< fa file-powerpoint size=2xl >}}](/aulas/Inferencias_Medias/Teste_medias.html#/testes-para-duas-populações "Testes para duas populações"){aria-label="Testes para duas populações"} | |[{{< fa file-lines size=2xl >}}️   ](/exercicios/lista01.html "Lista de Exercícios 01"){aria-label="Lista de Exercícios 01"} | | | |
|  [5](programacao/semana-5.html)  | Sex, 06/06 | Inferência sobre matrizes de covariâncias | | [{{< fa file-powerpoint size=2xl >}}](/aulas/Inferencia_Covariancias/Teste_covariancias.html#/teste-para-uma-covariância-específica-4 "Testes para matrizes de covariâncias"){aria-label="Testes para matrizes de covariâncias"} | | | | | |
|  [6](programacao/semana-6.html)  | Sex, 13/06 | Análise de variância multivariada - MANOVA  | | [{{< fa file-powerpoint size=2xl >}}](/aulas/Manova/manova.html#/manova-uma-generalização-da-anova "MANOVA"){aria-label="MANOVA"} | |[{{< fa file-lines size=2xl >}}](/exercicios/lista02.html "Lista de Exercícios 02"){aria-label="Lista de Exercícios 02"} | | | |
|  [7](programacao/semana-7.html)  | Sex, 20/06 | Não haverá aula - recesso  | |  | || | | |
|  [8](programacao/semana-8.html)  | Sex, 27/06 | Análise de variância multivariada - MANOVA  | | [{{< fa file-powerpoint size=2xl >}}](/aulas/Manova/manova.html#/intervalos-simultâneos-de-confiança-para-efeitos-de-tratamento "Intervalo de confiança simultâneos"){aria-label="Intervalo de confiança simultâneos"} | |[{{< fa file-lines size=2xl >}}](/exercicios/lista03.html "Lista de Exercícios 03"){aria-label="Lista de Exercícios 03"} | | | |
|  [9](programacao/semana-9.html)  | Sex, 04/07 | Análise de regressão multivariada  | | [{{< fa file-powerpoint size=2xl >}}](/aulas/Regressao_Multivariada/regressao.html#/generalizando "Análise de regressão multivariada"){aria-label="Análise de regressão multivariada"} | | | | | |
|  [10](programacao/semana-10.html)  | Sex, 11/07 | Escalonamento Multidimensional  | | [{{< fa file-powerpoint size=2xl >}}](/aulas/Escalonamento/escalonamento.html "Escalonamento Multidimensional"){aria-label="Escalonamento Multidimensional"} | | | | | |
:::

```{r echo = FALSE}
knitr::knit_exit()
```

